### PR TITLE
suite_runner: fix deprecated debug mode argument

### PR DESCRIPTION
**Pull request by marcushultman**
fixes Auto Attach in vscode

### CODE REVIEW

**Comment by marcushultman** [comment]
@per-gron what about backwards compatibility? `--inspect` and `--inspect-brk` has been available from node 6.x.

**Comment by per-gron** [comment]
@marcushultman thanks for updating the test. I don't care that much about backwards compatibility to be honest. It's probably not a great idea to be using a node version that's from early 2016 or before...

**Comment by marcushultman** [comment]
@per-gron When and how are releases created? Are there any items on the roadmap for a new release? We could use overman from trunk, but if there is an npm release that would be better.

**Comment by marcushultman** [comment]
@per-gron ping

**Comment by per-gron** [comment]
@marcushultman There is no roadmap.

The process for a new version is simply bumping the version number in package.json and manually publishing to npm.

Are you working at Spotify? The only user of this library that I know of is there. If you do I can give you merge rights and npm publish rights so you can handle this yourself.

**Comment by marcushultman** [comment]
@per-gron Ok! Yes I do work at Spotify and we use it. Sounds good https://www.npmjs.com/settings/hultman/profile npm profile

**Comment by per-gron** [comment]
@marcushultman Ok! At the moment I am travelling and I have lost my phone so I'm currently locked out from doing these things. I'll get the phone back tomorrow. Then I will check your identity using some other means than Github and give you access.

**Comment by marcushultman** [comment]
@per-gron sounds good 👍

**Pull request merged**
